### ISSUE TITLE
ABCMeta object is not subscriptable

### ISSUE THREAD

**Issue by pablosolar** [vemel/handsdown#21]
Hello!!

First of all, thank you for your effort and work!

From my project directory:

_/Users/myuser/Workspace/my_project_

I am trying:

_handsdown -o docs_ 

But getting the following error:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/handsdown", line 6, in <module>
    from handsdown.main import main
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/handsdown/main.py", line 7, in <module>
    from handsdown.generator import Generator, GeneratorError
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/handsdown/generator.py", line 20, in <module>
    from handsdown.utils.nice_path import NicePath
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/handsdown/utils/nice_path.py", line 11, in <module>
    class NicePath(Path):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/handsdown/utils/nice_path.py", line 36, in NicePath
    self: _R, exclude: Iterable[Path] = tuple(), glob_pattern: str = "**/*"
TypeError: 'ABCMeta' object is not subscriptable_
```

Do you know that could be the issue? Thank you very much!

**Comment by vemel** [comment]
FIxed in  `main`. As I see, you a using git checkout version, so please pull the changes.
